# Generated by Django 6.0.3 on 2026-03-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_domain_slug_report_usergoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='aggregation_type',
            field=models.CharField(choices=[('sum', 'Sum'), ('avg', 'Avg'), ('max', 'Max'), ('min', 'Min'), ('last', 'Last')], max_length=10),
        ),
        migrations.AlterField(
            model_name='metric',
            name='unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('minutes', 'Minutes'), ('count', 'Count'), ('points', 'Points'), ('kg', 'Kilograms'), ('kcal', 'Kilocalories'), ('g', 'Grams'), ('ml', 'Milliliters'), ('km', 'Kilometers'), ('custom', 'Custom')], max_length=20),
        ),
    ]
