# Generated by Django 6.0.3 on 2026-03-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_alter_metric_aggregation_type_alter_metric_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('mind', 'Mind'), ('body', 'Body'), ('spirit', 'Spirit')], max_length=10),
        ),
    ]
